### ISSUE TITLE
strings.xml

### ISSUE THREAD

**Issue by hockhun** [TheAndroidMaster/Wallpapers#2]
Hello. How can i add a new images into strings.xml? Any sample for beginers?

**Comment by fennifith** [comment]
No clue, can't remember. Haven't worked on this project for ages. I don't recommend using it for anything. Should probably update the readme to say it's deprecated. Maybe use [Frames](https://github.com/jahirfiquitiva/Frames) instead, since it's a looooot more recent.

**Comment by fennifith** [comment]
Well, I've updated the readme to explicitly state that this project is a useless piece of crap. Closing.
